package pipeline.runtime;

/*Generated by MPS */

import java.util.List;
import java.util.concurrent.ConcurrentLinkedQueue;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public class ConcatenateTexts extends Filter<TextItem, TextItem> {

  private List<Filter<?, TextItem>> inputs;
  private ConcurrentLinkedQueue<TextItem> output;

  public ConcatenateTexts(Filter<?, TextItem>... inputs) {
    this.inputs = ListSequence.fromList(new LinkedList<Filter<?, TextItem>>());
    for (Filter<?, TextItem> filter : inputs) {
      if (filter != null) {
        ListSequence.fromList(this.inputs).addElement(filter);
      }
    }
    output = new ConcurrentLinkedQueue<TextItem>();
  }

  @Override
  public void run() {
    for (Filter<?, TextItem> filter : inputs) {
      filter.start();
    }

    output.add(new TextItem(Item.State.KEY_WORD, TextItem.BEGIN_OF_TEXT));

    for (Filter<?, TextItem> filter : inputs) {
      TextItem item = filter.getItem();

      while (!((item.getState() == Item.State.KEY_WORD && item.getValue().equals(TextItem.END_OF_TEXT)))) {
        if (item.getState() == Item.State.STR) {
          output.add(new TextItem(Item.State.STR, item.getValue() + " "));
        }
        item = filter.getItem();
      }
    }

    output.add(new TextItem(Item.State.KEY_WORD, TextItem.END_OF_TEXT));
  }

  @Override
  public TextItem getItem() {
    TextItem item = output.poll();
    if (item == null) {
      return new TextItem(Item.State.EMPTY, null);
    } else {
      return item;
    }
  }
}
