package pipeline.runtime;

/*Generated by MPS */

import java.util.List;
import java.util.concurrent.ConcurrentLinkedQueue;

public interface IFilter extends Runnable {
  List<ConcurrentLinkedQueue> getQueueList();
  ConcurrentLinkedQueue getFirstOutput();
}
