package pipeline.runtime;

/*Generated by MPS */


public class Item {
  public enum State {
    STR(),
    EMPTY(),
    KEY_WORD()
  }

  private Item.State state;
  private String value;

  public Item(Item.State state, String value) {
    this.state = state;
    this.value = value;
  }

  public Item.State getState() {
    return state;
  }

  public void setState(Item.State state) {
    this.state = state;
  }

  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }
}
