package pipeline.runtime;

/*Generated by MPS */

import java.util.List;
import java.util.concurrent.ConcurrentLinkedQueue;

public class SplitSentence implements IFilter {
  public SplitSentence() {
    System.out.println("SplitSentence created");
  }
  @Override
  public void run() {
  }

  @Override
  public List<ConcurrentLinkedQueue> getQueueList() {
    return null;
  }

  @Override
  public ConcurrentLinkedQueue getFirstOutput() {
    return null;
  }
}
