package pipeline.runtime;

/*Generated by MPS */


public class SplitSentence extends Filter<SentenceItem, Item> {
  public SplitSentence() {
    System.out.println("SplitSentence created");
  }
  @Override
  public void run() {
  }

  @Override
  public Item getItem() {
    return null;
  }
}
