package pipeline.runtime;

/*Generated by MPS */


public class TextItem extends Item {
  public static final String END_OF_TEXT = "<END_OF_TEXT>";
  public static final String BEGIN_OF_TEXT = "<BEGIN_OF_TEXT>";

  public TextItem(Item.State state, String value) {
    super(state, value);
  }
}
