package pipeline.sandbox;

/*Generated by MPS */

import java.io.PrintWriter;
import pipeline.runtime.Filter;
import java.io.FileOutputStream;
import java.io.FileNotFoundException;
import pipeline.runtime.Item;
import pipeline.runtime.TextItem;
import pipeline.runtime.MergeSentences;
import pipeline.runtime.MergeTokens;
import pipeline.runtime.SplitSentence;
import pipeline.runtime.SplitText;
import pipeline.runtime.Reader;

public class SimplePipeline {
  private class Writer extends Thread {
    private PrintWriter output;
    private Filter input;

    public Writer(String filename, Filter input) {
      try {
        output = new PrintWriter(new FileOutputStream(filename), true);
      } catch (FileNotFoundException e) {
        e.printStackTrace();
      }
      this.input = input;
    }
    @Override
    public void run() {
      Item item = input.getItem();

      while (!((item.getState() == Item.State.KEY_WORD && item.getValue().equals(TextItem.END_OF_TEXT)))) {
        if (item.getState() != Item.State.EMPTY && !(item.isBeginOfText())) {
          output.write(item.getValue());
        }
        item = input.getItem();
      }
      System.out.println("Writer finished!");
      output.close();
    }
  }

  private SimplePipeline.Writer writer;
  private Filter filter;

  public SimplePipeline() {
    System.out.println("Init start");
    filter = new MergeSentences(new MergeTokens(new SplitSentence(new SplitText(new Reader("/home/yulya/MPSProjects/my_pipeline/pipeline/input.txt")))));
    writer = new SimplePipeline.Writer("/home/yulya/MPSProjects/my_pipeline/pipeline/output.txt", filter);
    System.out.println("Init finish");
  }

  public void myRun() {
    filter.start();
    writer.start();
    try {
      filter.join();
      writer.join();
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
  }

  public static void main(String[] args) {
    System.out.println("main()");
    (new SimplePipeline()).myRun();
  }
}
