package pipeline.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptFilter = createDescriptorForFilter();
  /*package*/ final ConceptDescriptor myConceptPath = createDescriptorForPath();
  /*package*/ final ConceptDescriptor myConceptPipeline = createDescriptorForPipeline();
  /*package*/ final ConceptDescriptor myConceptSplitSentence = createDescriptorForSplitSentence();
  /*package*/ final ConceptDescriptor myConceptSplitText = createDescriptorForSplitText();
  /*package*/ final ConceptDescriptor myConcepttoEnglish = createDescriptorFortoEnglish();
  /*package*/ final ConceptDescriptor myConcepttoLower = createDescriptorFortoLower();
  private final LanguageConceptSwitch myConceptIndex;

  public StructureAspectDescriptor() {
    myConceptIndex = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptFilter, myConceptPath, myConceptPipeline, myConceptSplitSentence, myConceptSplitText, myConcepttoEnglish, myConcepttoLower);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myConceptIndex.index(id)) {
      case LanguageConceptSwitch.Filter:
        return myConceptFilter;
      case LanguageConceptSwitch.Path:
        return myConceptPath;
      case LanguageConceptSwitch.Pipeline:
        return myConceptPipeline;
      case LanguageConceptSwitch.SplitSentence:
        return myConceptSplitSentence;
      case LanguageConceptSwitch.SplitText:
        return myConceptSplitText;
      case LanguageConceptSwitch.toEnglish:
        return myConcepttoEnglish;
      case LanguageConceptSwitch.toLower:
        return myConcepttoLower;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myConceptIndex.index(c);
  }

  private static ConceptDescriptor createDescriptorForFilter() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pipeline", "Filter", 0x7655a5e7076c42d6L, 0xb8853f94b3d29c6bL, 0x2a3c2aa1feea76a4L);
    b.interface_();
    b.origin("r:5b671864-0da2-4a56-aca4-190af62444b8(pipeline.structure)/3043354323450492580");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPath() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pipeline", "Path", 0x7655a5e7076c42d6L, 0xb8853f94b3d29c6bL, 0x2a3c2aa1ff0f8a8eL);
    b.class_(false, false, false);
    b.origin("r:5b671864-0da2-4a56-aca4-190af62444b8(pipeline.structure)/3043354323452922510");
    b.prop("value", 0x2a3c2aa1ff0f8afbL, "3043354323452922619");
    b.alias("path");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPipeline() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pipeline", "Pipeline", 0x7655a5e7076c42d6L, 0xb8853f94b3d29c6bL, 0x5433b88ac5b47d87L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:5b671864-0da2-4a56-aca4-190af62444b8(pipeline.structure)/6067396029160127879");
    b.aggregate("input", 0x2a3c2aa1ff106569L).target(0x7655a5e7076c42d6L, 0xb8853f94b3d29c6bL, 0x2a3c2aa1ff0f8a8eL).optional(false).ordered(true).multiple(false).origin("3043354323452978537").done();
    b.aggregate("output", 0x2a3c2aa1ff10656eL).target(0x7655a5e7076c42d6L, 0xb8853f94b3d29c6bL, 0x2a3c2aa1ff0f8a8eL).optional(false).ordered(true).multiple(false).origin("3043354323452978542").done();
    b.aggregate("filters", 0x2a3c2aa1ff11e24fL).target(0x7655a5e7076c42d6L, 0xb8853f94b3d29c6bL, 0x2a3c2aa1feea76a4L).optional(true).ordered(true).multiple(true).origin("3043354323453076047").done();
    b.alias("pipeline");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSplitSentence() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pipeline", "SplitSentence", 0x7655a5e7076c42d6L, 0xb8853f94b3d29c6bL, 0x2a3c2aa1fee9ce93L);
    b.class_(false, false, false);
    b.parent(0x7655a5e7076c42d6L, 0xb8853f94b3d29c6bL, 0x2a3c2aa1feea76a4L);
    b.origin("r:5b671864-0da2-4a56-aca4-190af62444b8(pipeline.structure)/3043354323450449555");
    b.alias("SentenceToTokens");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSplitText() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pipeline", "SplitText", 0x7655a5e7076c42d6L, 0xb8853f94b3d29c6bL, 0x5433b88ac5b47dabL);
    b.class_(false, false, false);
    b.parent(0x7655a5e7076c42d6L, 0xb8853f94b3d29c6bL, 0x2a3c2aa1feea76a4L);
    b.origin("r:5b671864-0da2-4a56-aca4-190af62444b8(pipeline.structure)/6067396029160127915");
    b.alias("splitText");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorFortoEnglish() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pipeline", "toEnglish", 0x7655a5e7076c42d6L, 0xb8853f94b3d29c6bL, 0x2a3c2aa1fee9d9adL);
    b.class_(false, false, false);
    b.parent(0x7655a5e7076c42d6L, 0xb8853f94b3d29c6bL, 0x2a3c2aa1feea76a4L);
    b.origin("r:5b671864-0da2-4a56-aca4-190af62444b8(pipeline.structure)/3043354323450452397");
    b.alias("TranslaitTokensToEnglish");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorFortoLower() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pipeline", "toLower", 0x7655a5e7076c42d6L, 0xb8853f94b3d29c6bL, 0x2a3c2aa1fee9d938L);
    b.class_(false, false, false);
    b.parent(0x7655a5e7076c42d6L, 0xb8853f94b3d29c6bL, 0x2a3c2aa1feea76a4L);
    b.origin("r:5b671864-0da2-4a56-aca4-190af62444b8(pipeline.structure)/3043354323450452280");
    b.alias("TokensToLowerCase");
    return b.create();
  }
}
